name: Build

on:
  push:
    branches: [ legacy ]
  pull_request:
    branches: [ legacy ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: "adopt"
          java-version: 8
          cache: "gradle"
      - name: Build
        run: ./gradlew build
      - name: Upload artifact
        run: |
          cd build/libs
          export JAR=$(find . -regex '.*airplus-b[0-9|.]*\.jar')
          export AP_VERSION=$(echo $JAR | sed -r 's/.\/airplus-([a-zA-Z][0-9]+)\.jar/\1/')
          export MINECRAFT_VERSION='1.8.9'
          echo Version: $AP_VERSION, Minecraft: $MINECRAFT_VERSION
          cp $JAR zip/airplus.jar
          cd zip
          zip -r airplus.zip *
          md5sum airplus.zip